### PR TITLE
Add a method to show Ui in a separate thread

### PR DESCRIPTION
**Pull request by sridharbaldava**
I sometimes find it useful to launch the addin UIs on their separate thread as it keeps it disentangled from the main Revit UI. Feel free to disregard this.

### CODE REVIEW

**Review by mitevpi — COMMENTED** [review]
I like the idea, but the external methods don't work when using the `ShowFormSeperateThread` method.

This is the output using the `ShowForm` method:
image

When you try and execute the same methods from an instance that was initialized with `ShowFormSeperateThread`, there's no output in the text box. 

`TaskDialog.Show()` also doesn't seem to work when using the `ShowFormSeperateThread` method to initialize.

image

**Comment by sridharbaldava** [comment]
Thanks for reviewing this. It doesn't throw any errors and fails silently which is surprising. I'd expect all external methods to work. However, I can only get the string arg method to work, but, the WPF arg methods don't seem to do anything. Again without any errors. I'll look into this some more later. Might need to create a different UI template for the separate thread option.

**Comment by sridharbaldava** [comment]
I thought about it a bit more. It would definitely need a different UI implementation. 
```c#
        public override void Execute(UIApplication uiApp, Ui ui)
        {
            // SETUP
            UIDocument uiDoc = uiApp.ActiveUIDocument;
            Document doc = uiDoc.Document;

            // METHODS
            if (ui.CbDocumentData.IsChecked == true)
```
That last line will fail as Execute is being called under the Revit Context and Ui is in a separate thread. Using a dispatcher here might work, but, better solution/guidance would be to separate Ui methods from the Revit Execute context by using a viewmodel in between.

**Comment by sridharbaldava** [comment]
I've made it work with using a dispatcher. External methods will still not work as they are not in the Revit context. For testing I also created a separate button for the Ui window that is launched in separate thread. I have creatively named it as Revit Template 2.

**Comment by mitevpi** [comment]
Awesome! Thanks for looking into this. I'll try to find some time to pull it locally and test on my machine again - just a bit busy with work recently :)

**Comment by mitevpi** [comment]
@sridharbaldava  Hey thanks again for doing this, I had a chance to review and it seems to work very well! Going to merge this and do a bit more cleanup, but I think I may even make your `ShowForm` the default rather than the single-threaded one. Really interesting pattern - thanks for sharing.

**Pull request merged**
